meta-mender-tegra: improve commit and rollback handling in tegra-state-scripts
* Split the rollback state script in two - pre-reboot and post-reboot.
  Mark the current (rolled-back-to) boot slot successful post-reboot.

* When using U-Boot on TX2, a boot failure detected after U-Boot takes
  control would desyncrhonize the the Tegra boot slot and Mender's
  rootfs slot.  Have the ArtifactRollback_Leave state script detect
  this and switch the boot slot to resynchronize them.

* Also with U-Boot on TX2, a failure in the Tegra bootloader (before
  U-Boot takes over) would cause the processor to switch boot slots
  back to the good one, and Mender would happily mark that boot as
  successful since U-Boot didn't detect the problem. To deal with
  this, add an ArtifactCommit_Enter state script to check that
  the boot slot matches the rootfs slot and if not, return an error
  so Mender rolls back the update.

* Remove the '-e' from the #! lines of the scripts.  Some use expr,
  which returns a non-zero status if the resulting expression is zero,
  and that was causing error exits from the script.

Signed-off-by: Matt Madison <matt@madison.systems>

diff --git a/meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-commit-script b/meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-commit-script
--- a/meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-commit-script
+++ b/meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-commit-script
@@ -2,7 +2,7 @@
 echo "Notifying NV bootloader of successful upgrade"
 curslot=`nvbootctrl get-current-slot`
 if ! nvbootctrl mark-boot-successful; then
-    echo "ERR: could not restore boot-succesful status for slot: $curslot" >&2
+    echo "ERR: could not set boot-succesful status for slot: $curslot" >&2
     exit 1
 fi
 echo "Marked boot slot $curslot as successful"
