tegra: Fix potential issue, add checking of return code when trying to enable A/B update.
Changelog: Title
Signed-off-by: Ilies CHERGUI <ilies.chergui@touchsurgery.com>
Signed-off-by: Kurt Kiefer <kekiefer@gmail.com>

diff --git a/meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-install-script b/meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-install-script
--- a/meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-install-script
+++ b/meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-install-script
@@ -23,6 +23,10 @@ num_slots=`nvbootctrl get-number-slots`
 if [ $num_slots != 2 ]; then
     echo "Enabling A/B update mode using nv_update_engine"
     nv_update_engine --enable-ab
+    if [ ! "$?" -eq 0 ]; then
+        echo "ERR: could not enable A/B update by using nv_update_engine" >&2
+        exit 1
+    fi
 fi
 current_slot=`nvbootctrl get-current-slot`
 echo "Current boot slot: $current_slot"
