meta-mender-tegra: update state scripts for R32.3.1
for handling the dynamic generation of /etc/nv_boot_control.conf at
runtime.

Signed-off-by: Matt Madison <matt@madison.systems>

diff --git a/meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-install-script-uboot b/meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-install-script-uboot
--- a/meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-install-script-uboot
+++ b/meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-install-script-uboot
@@ -44,7 +44,14 @@ mount --bind /proc "${mnt}/proc"
 mount --bind /dev "${mnt}/dev"
 # Run the update engine in the context of the just-installed rootfs
 # to ensure that the TNSPEC in the config file it uses matches the
-# TNSPEC in the update payload
+# TNSPEC in the update payload. But first we have to set up the
+# configuration file with the TNSPEC.
+if [ -L "${mnt}/etc/nv_boot_control.conf" -a -x "${mnt}/usr/bin/setup-nv-boot-control" ]; then
+    rm "${mnt}/etc/nv_boot_control.conf"
+    if ! chroot "${mnt}" /usr/bin/setup-nv-boot-control; then
+	echo "ERR: could not initialize nv_boot_control.conf in new rootfs" >&2
+    fi
+fi
 if ! chroot "${mnt}" /usr/sbin/nv_update_engine --install no-reboot; then
     echo "ERR: bootloader update failed" >&2
     cleanup
