add jetpack 7 support, update `meta-mender-common`
adds wrynose support `meta-mender-tegra-common`

adds a jetpack 7 specific layer

diff --git a/meta-mender-tegra/meta-mender-tegra-common/recipes-bsp/u-boot/libubootenv-fake/fw_printenv b/meta-mender-tegra/meta-mender-tegra-common/recipes-bsp/u-boot/libubootenv-fake/fw_printenv
--- a/meta-mender-tegra/meta-mender-tegra-common/recipes-bsp/u-boot/libubootenv-fake/fw_printenv
+++ b/meta-mender-tegra/meta-mender-tegra-common/recipes-bsp/u-boot/libubootenv-fake/fw_printenv
@@ -1,77 +1,51 @@
 #!/bin/sh
-set -e
+LABELCHARS="AB"
 
 get_bootpart() {
-    _cfglbl='"RootfsPartA"'
-    _current_slot_cmd="nvbootctrl get-current-slot 2>/dev/null"
-    _check=$(command -v nvbootctrl 2>/dev/null || true)
-    if [ -z "${_check}" ]; then
-        _check=$(command -v tegra-boot-control 2>/dev/null || true)
-        if [ -z "${_check}" ]; then
-            echo "ERR: Neither nvbootctrl nor tegra-boot-control were found!"
-            exit 1
-        fi
-        _current_slot_cmd="tegra-boot-control --current-slot 2>/dev/null"
+    local current_slot=`nvbootctrl get-current-slot 2>/dev/null || tegra-boot-control --current-slot 2>/dev/null`
+    if [ -z "$current_slot" ]; then
+	echo "ERR: could not identify current boot slot" >&2
+	echo "UNKNOWN"
+	return
     fi
-
-    _current_slot="$(${_current_slot_cmd})"
-    if [ -z "${_current_slot}" ]; then
-        echo "ERR: could not identify current boot slot" >&2
-        echo "UNKNOWN"
-        return
-    fi
-
-    if [ "${_current_slot}" = "1" ]; then
-        _cfglbl='"RootfsPartB"'
-    fi
-
-    _devnam="$(grep -h "${_cfglbl}:" /etc/mender/mender.conf | tr -d '" ,' | grep -o '[0-9]\+$' || true)"
-    if [ -z "${_devnam}" ]; then
-      _devnam="$(grep -h "${_cfglbl}:" /var/lib/mender/mender.conf | tr -d '" ,' | grep -o '[0-9]\+$' || true)"
-    fi
-
-    if [ -z "${_devnam}" ]; then
-        echo "ERR: Could not find partition number for ${_cfglbl}" >&2
-        exit 1
-    fi
-    echo "${_devnam}"
+    local cfglbl="\"RootfsPart${LABELCHARS:$current_slot:1}\""
+    local devnam=`grep -h "$cfglbl:" /etc/mender/mender.conf /var/lib/mender/mender.conf | tr -d '" ,' | grep -o '[0-9]\+$'`
+    echo "$devnam"
 }
 
 quiet=
-if [ "${1}" = "-n" ]; then
+if [ "$1" = "-n" ]; then
     quiet="yes"
     shift
-    if [ -z "${1}" ]; then
+    if [ -z "$1" ]; then
         echo "ERR: missing var name with -n" >&2
         exit 1
     fi
 fi
-
 if [ -z "$1" ]; then
-    bootpart="$(get_bootpart)"
-    echo "mender_boot_part=${bootpart}"
+    bootpart=`get_bootpart`
+    echo "mender_boot_part=$bootpart"
     exit 0
 fi
-
-while [ -n "${1}" ]; do
-    case "${1}" in
+while [ -n "$1" ]; do
+    case "$1" in
         mender_boot_part)
-            bootpart="$(get_bootpart)"
-            [ -n "${quiet}" ] || printf "%s=" "${1}"
-            echo "${bootpart}"
+            bootpart=`get_bootpart`
+            [ -n "$quiet" ] || echo -n "$1="
+            echo "$bootpart"
             ;;
         mender_boot_part_hex)
-            bootpart="$(get_bootpart)"
-            bootpart_hex="$(echo "16o${bootpart}p" | dc)"
-            [ -n "${quiet}" ] || printf "%s=" "${1}"
-            echo "${bootpart_hex}"
+            bootpart=`get_bootpart`
+            bootpart_hex=`echo 16o${bootpart}p | dc`
+            [ -n "$quiet" ] || echo -n "$1="
+            echo "$bootpart_hex"
             ;;
         mender_uboot_separator)
-            [ -n "${quiet}" ] || printf "%s=" "${1}"
+            [ -n "$quiet" ] || echo -n "$1="
             echo "something other than just 1"
             ;;
         upgrade_available)
-            [ -n "${quiet}" ] || printf "%s=" "${1}"
+            [ -n "$quiet" ] || echo -n "$1="
             if [ -e "/var/lib/mender/upgrade_available" ]; then
                 echo "1"
             else
@@ -79,11 +53,11 @@ while [ -n "${1}" ]; do
             fi
             ;;
         mender_check_saveenv_canary)
-            [ -n "${quiet}" ] || printf "%s=" "${1}"
+            [ -n "$quiet" ] || echo -n "$1="
             echo "0"
             ;;
         *)
-           echo "ERR: no such variable: ${1}" >&2
+           echo "ERR: no such variable: $1" >&2
            exit 1
     esac
     shift
diff --git a/meta-mender-tegra/meta-mender-tegra-common/recipes-mender/tegra-state-scripts/files/switch-rootfs b/meta-mender-tegra/meta-mender-tegra-common/recipes-mender/tegra-state-scripts/files/switch-rootfs
--- a/meta-mender-tegra/meta-mender-tegra-common/recipes-mender/tegra-state-scripts/files/switch-rootfs
+++ b/meta-mender-tegra/meta-mender-tegra-common/recipes-mender/tegra-state-scripts/files/switch-rootfs
@@ -1,56 +1,46 @@
-#!/usr/bin/env sh
+#!/bin/sh
 set -e
-
 echo "$(mender-update show-artifact): $(basename "$0") was called!" >&2
 
 get_bootpart() {
-    _current_slot_cmd="nvbootctrl get-current-slot 2>/dev/null"
-    _check=$(command -v nvbootctrl 2>/dev/null || true)
-    if [ -z "${_check}" ]; then
-        _check=$(command -v tegra-boot-control 2>/dev/null || true)
-        if [ -z "${_check}" ]; then
-            echo "ERR: Neither nvbootctrl nor tegra-boot-control where found!"
-            exit 1
-        fi
-        _current_slot_cmd="tegra-boot-control --current-slot 2>/dev/null"
-    fi
-
-    _current_slot="$(${_current_slot_cmd})"
-    if [ -z "${_current_slot}" ]; then
-            echo "ERR: could not identify current boot slot" >&2
-            echo "UNKNOWN"
-            return
-        fi
-    echo "${_current_slot}"
+	local current_slot=`nvbootctrl get-current-slot 2>/dev/null`
+	if [ -z "$current_slot" ]; then
+    		echo "ERR: could not identify current boot slot" >&2
+    		echo "UNKNOWN"
+    		return
+    	fi
+	echo "$current_slot"
 }
 
 reset_unbootable_status() {
-    . /usr/bin/uefi_common.func
-    _slot="SlotA"
-    if [ "${1}" = "1" ]; then
-        _slot="SlotB"
-    fi
-    _value="\x00\x00\x00\x00"
-    set_efi_var "RootfsStatus${_slot}" "781e084c-a330-417c-b678-38e696380cb9" "${_value}"
+	source /usr/bin/uefi_common.func
+
+	local AB="AB"
+	local slot="Slot${AB:$1:1}"
+	local value="\x00\x00\x00\x00"
+	set_efi_var "RootfsStatus${slot}" "781e084c-a330-417c-b678-38e696380cb9" "$value"
 }
 
-current_slot="$(get_bootpart)"
-echo "current_slot=${current_slot}" >&2
+current_slot=`get_bootpart`
+echo "current_slot=$current_slot" >&2
 
-next_slot="0"
-next_rootfs_dev="/dev/disk/by-partlabel/APP"
-if [ "${current_slot}" = "0" ]; then
-    next_slot="1"
-    next_rootfs_dev="/dev/disk/by-partlabel/APP_b"
+next_slot=
+next_rootfs_dev=
+if [ $current_slot = "0" ]; then
+	next_slot="1"
+	next_rootfs_dev="/dev/disk/by-partlabel/APP_b"
+else
+	next_slot="0"
+	next_rootfs_dev="/dev/disk/by-partlabel/APP"
 fi
 
-tmp_mount="$(mktemp -d)"
+tmp_mount=`mktemp -d`
 
-reset_unbootable_status "${next_slot}"
+reset_unbootable_status $next_slot
 mkdir -p /boot/efi/EFI/UpdateCapsule
-mount -o ro "${next_rootfs_dev}" "${tmp_mount}"
-cp "${tmp_mount}"/opt/nvidia/UpdateCapsule/tegra-bl.cap /boot/efi/EFI/UpdateCapsule/TEGRA_BL.Cap
-umount "${tmp_mount}"
+mount -o ro $next_rootfs_dev $tmp_mount
+cp ${tmp_mount}/opt/nvidia/UpdateCapsule/tegra-bl.cap /boot/efi/EFI/UpdateCapsule/TEGRA_BL.Cap
+umount $tmp_mount
 oe4t-set-uefi-OSIndications
 
 exit 0
